var initialCourseArray = new Array();
initialCourseArray = [
{"name":"ENGL1013","seasonRestrict":"n","hours":"3","Prereqs":"end","summer":"1","ULE":"1","label":"ENGL 1013","link":"https:\/\/www.atu.edu\/academics\/descriptions\/?subject=ENGL&number=1013"},
{"name":"GE_SS1","seasonRestrict":"n","hours":"4","Prereqs":"end","summer":"1","ULE":"2","label":"Science","link":"https:\/\/www.atu.edu\/academics\/dev\/catalog\/graduation-requirements.html#GenEdRequirements"},
{"name":"MATH2243","seasonRestrict":"n","hours":"3","Prereqs":"end","summer":"1","ULE":"1","label":"MATH 2243","link":"https:\/\/www.atu.edu\/academics\/descriptions\/?subject=MATH&number=2243"},
{"name":"TECH1001","seasonRestrict":"n","hours":"1","Prereqs":"end","summer":"1","label":"TECH 1001","link":"https:\/\/www.atu.edu\/academics\/descriptions\/?subject=TECH&number=1001"},
{"name":"COMS1403","seasonRestrict":"n","hours":"3","Prereqs":"co|COMS1411|end","summer":"0","label":"COMS 1403","link":"https:\/\/www.atu.edu\/academics\/descriptions\/?subject=COMS&number=1403"},
{"name":"COMS1411","seasonRestrict":"n","hours":"1","Prereqs":"co|COMS1403|end","summer":"0","label":"COMS 1411","link":"https:\/\/www.atu.edu\/academics\/descriptions\/?subject=COMS&number=1411"},
{"name":"ENGL1023","seasonRestrict":"n","hours":"3","Prereqs":"ENGL1013|end","summer":"1","ULE":"1","label":"ENGL 1023","link":"https:\/\/www.atu.edu\/academics\/descriptions\/?subject=ENGL&number=1023"},
{"name":"GE_HIST1","seasonRestrict":"n","hours":"3","Prereqs":"end","summer":"1","ULE":"2","label":"History","link":"https:\/\/www.atu.edu\/academics\/dev\/catalog\/graduation-requirements.html#GenEdRequirements"},
{"name":"ECON2003","seasonRestrict":"n","hours":"3","Prereqs":"end","summer":"1","label":"ECON 2003","link":"https:\/\/www.atu.edu\/academics\/descriptions\/?subject=ECON&number=2003"},
{"name":"COMS1333","seasonRestrict":"n","hours":"3","Prereqs":"COMS1003|end","summer":"1","ULE":"1","label":"COMS 1333","link":"https:\/\/www.atu.edu\/academics\/descriptions\/?subject=COMS&number=1333"},
{"name":"COMS2104","seasonRestrict":"n","hours":"4","Prereqs":"COMS1403|COMS1411|end","summer":"0","ULE":"1","label":"COMS 2104","link":"https:\/\/www.atu.edu\/academics\/descriptions\/?subject=COMS&number=2104"},
{"name":"ENGL2053","seasonRestrict":"n","hours":"3","Prereqs":"ENGL1023|end","summer":"1","ULE":"1","label":"ENGL 2053","link":"https:\/\/www.atu.edu\/academics\/descriptions\/?subject=ENGL&number=2053"},
{"name":"COMS2203","seasonRestrict":"n","hours":"3","Prereqs":"COMS2104|end","summer":"0","ULE":"1","label":"COMS 2203","link":"https:\/\/www.atu.edu\/academics\/descriptions\/?subject=COMS&number=2203"},
{"name":"COMS2333","seasonRestrict":"n","hours":"3","Prereqs":"COMS1333|end","summer":"0","ULE":"1","label":"COMS 2333","link":"https:\/\/www.atu.edu\/academics\/descriptions\/?subject=COMS&number=2333"},
{"name":"COMS2700","seasonRestrict":"n","hours":"0","Prereqs":"co|COMS2703|end","summer":"0","label":"COMS 2700","link":"https:\/\/www.atu.edu\/academics\/descriptions\/?subject=COMS&number=2700"},
{"name":"COMS2703","seasonRestrict":"n","hours":"3","Prereqs":"co|COMS2700|COMS1411|COMS1403|end","summer":"0","label":"COMS 2703","link":"https:\/\/www.atu.edu\/academics\/descriptions\/?subject=COMS&number=2703"},
{"name":"COMS2903","seasonRestrict":"n","hours":"3","Prereqs":"COMS2104|end","summer":"0","ULE":"1","label":"COMS 2903","link":"https:\/\/www.atu.edu\/academics\/descriptions\/?subject=COMS&number=2903"},
{"name":"BUAD2053","seasonRestrict":"n","hours":"3","Prereqs":"COMS2003|MATH2243|end","summer":"1","ULE":"1","label":"BUAD 2053","link":"https:\/\/www.atu.edu\/academics\/descriptions\/?subject=BUAD&number=2053"},
{"name":"COMS2003","seasonRestrict":"n","hours":"3","Prereqs":"COMS1003|end","summer":"1","ULE":"1","label":"COMS 2003","link":"https:\/\/www.atu.edu\/academics\/descriptions\/?subject=COMS&number=2003"},
{"name":"COMS2213","seasonRestrict":"n","hours":"3","Prereqs":"COMS2203|COMS2903|end","summer":"0","label":"COMS 2213","link":"https:\/\/www.atu.edu\/academics\/descriptions\/?subject=COMS&number=2213"},
{"name":"COMS2713","seasonRestrict":"s","hours":"3","Prereqs":"COMS1411|COMS1403|end","summer":"0","ULE":"1","label":"COMS 2713","link":"https:\/\/www.atu.edu\/academics\/descriptions\/?subject=COMS&number=2713"},
{"name":"COMS2733","seasonRestrict":"s","hours":"3","Prereqs":"co|COMS2713|COMS2703|end","summer":"0","label":"COMS 2733","link":"https:\/\/www.atu.edu\/academics\/descriptions\/?subject=COMS&number=2733"},
{"name":"GE_FAH1","seasonRestrict":"n","hours":"3","Prereqs":"end","summer":"1","ULE":"2","label":"Fine Arts","link":"https:\/\/www.atu.edu\/academics\/dev\/catalog\/graduation-requirements.html#GenEdRequirements"},
{"name":"SPH2173","seasonRestrict":"n","hours":"3","Prereqs":"end","summer":"1","label":"SPH 2173","link":"https:\/\/www.atu.edu\/academics\/descriptions\/?subject=SPH&number=2173"},
{"name":"COMS3233","seasonRestrict":"n","hours":"3","Prereqs":"COMS2003|COMS2203|COMS2903|end","summer":"0","label":"COMS 3233","link":"https:\/\/www.atu.edu\/academics\/descriptions\/?subject=COMS&number=3233"},
{"name":"COMS3903","seasonRestrict":"f","hours":"3","Prereqs":"COMS2703|COMS2104|end","summer":"0","ULE":"1","label":"COMS 3903","link":"https:\/\/www.atu.edu\/academics\/descriptions\/?subject=COMS&number=3903"},
{"name":"COMS4313","seasonRestrict":"f","hours":"3","Prereqs":"COMS2333|COMS2733|end","summer":"0","label":"COMS 4313","link":"https:\/\/www.atu.edu\/academics\/descriptions\/?subject=COMS&number=4313"},
{"name":"GE_SS2","seasonRestrict":"n","hours":"4","Prereqs":"end","summer":"1","ULE":"2","label":"Science","link":"https:\/\/www.atu.edu\/academics\/dev\/catalog\/graduation-requirements.html#GenEdRequirements"},
{"name":"COMS2163","seasonRestrict":"s","hours":"3","Prereqs":"end","summer":"0","ULE":"1","label":"COMS 2163","link":"https:\/\/www.atu.edu\/academics\/descriptions\/?subject=COMS&number=2163"},
{"name":"COMS3523","seasonRestrict":"s","hours":"3","Prereqs":"end","summer":"0","ULE":"1","label":"COMS 3523","link":"https:\/\/www.atu.edu\/academics\/descriptions\/?subject=COMS&number=3523"},
{"name":"COMS4700","seasonRestrict":"n","hours":"0","Prereqs":"co|COMS4703|end","summer":"0","label":"COMS 4700","link":"https:\/\/www.atu.edu\/academics\/descriptions\/?subject=COMS&number=4700"},
{"name":"COMS4703","seasonRestrict":"n","hours":"3","Prereqs":"co|COMS4700|COMS2703|COMS2903|COMS2223|end","summer":"0","ULE":"1","label":"COMS 4703","link":"https:\/\/www.atu.edu\/academics\/descriptions\/?subject=COMS&number=4703"},
{"name":"GE_UPPR","seasonRestrict":"n","hours":"1","Prereqs":"end","summer":"1","ULE":"2","label":"UL Elective","link":"https:\/\/www.atu.edu\/academics\/catalog\/colleges\/applied_sciences\/dept_comp_info_sci.html#InformationTechnology"},
{"name":"GE_SOCS1","seasonRestrict":"n","hours":"3","Prereqs":"end","summer":"1","ULE":"2","label":"SocScience","link":"https:\/\/www.atu.edu\/academics\/dev\/catalog\/graduation-requirements.html#GenEdRequirements"},
{"name":"COMS4033","seasonRestrict":"n","hours":"3","Prereqs":"COMS3233|end","summer":"0","label":"COMS 4033","link":"https:\/\/www.atu.edu\/academics\/descriptions\/?subject=COMS&number=4033"},
{"name":"COMS4213","seasonRestrict":"f","hours":"3","Prereqs":"COMS3233|end","summer":"0","label":"COMS 4213","link":"https:\/\/www.atu.edu\/academics\/descriptions\/?subject=COMS&number=4213"},
{"name":"COMS4713","seasonRestrict":"f","hours":"3","Prereqs":"co|COMS4710|COMS4703|end","summer":"0","label":"COMS 4713","link":"https:\/\/www.atu.edu\/academics\/descriptions\/?subject=COMS&number=4713"},
{"name":"COMS4710","seasonRestrict":"f","hours":"0","Prereqs":"co|COMS4713|end","summer":"0","label":"COMS 4710","link":"https:\/\/www.atu.edu\/academics\/descriptions\/?subject=COMS&number=4710"},
{"name":"COMS_ELEC","seasonRestrict":"n","hours":"3","Prereqs":"end","summer":"1","ULE":"2","label":"COMS Elec","link":"https:\/\/www.atu.edu\/academics\/catalog\/colleges\/applied_sciences\/dept_comp_info_sci.html#InformationTechnology"},
{"name":"GE_FAH2","seasonRestrict":"n","hours":"3","Prereqs":"end","summer":"1","ULE":"2","label":"Fine Arts","link":"https:\/\/www.atu.edu\/academics\/dev\/catalog\/graduation-requirements.html#GenEdRequirements"},
{"name":"COMS3053","seasonRestrict":"n","hours":"3","Prereqs":"end","summer":"1","ULE":"1","label":"COMS 3053","link":"https:\/\/www.atu.edu\/academics\/descriptions\/?subject=COMS&number=3053"},
{"name":"COMS4043","seasonRestrict":"n","hours":"3","Prereqs":"COMS4033|end","summer":"0","ULE":"1","label":"COMS 4043","link":"https:\/\/www.atu.edu\/academics\/descriptions\/?subject=COMS&number=4043"},
{"name":"COMS4063","seasonRestrict":"s","hours":"3","Prereqs":"end","summer":"0","ULE":"1","label":"COMS 4063","link":"https:\/\/www.atu.edu\/academics\/descriptions\/?subject=COMS&number=4063"},
{"name":"GE_UPPR2","seasonRestrict":"n","hours":"3","Prereqs":"end","summer":"1","ULE":"2","label":"UL Elective","link":"https:\/\/www.atu.edu\/academics\/catalog\/colleges\/applied_sciences\/dept_comp_info_sci.html#InformationTechnology"},
false]; 